# Generated by Django 5.1.3 on 2025-05-14 15:24

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Character Role',
                'verbose_name_plural': 'Character Roles',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.characters.models.Character.avatar_path)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alignment', models.CharField(choices=[('lawfull_good', 'Lawfull Good'), ('neutral_good', 'Neutral Good'), ('chaotic_good', 'Chaotic Good'), ('lawfull_neutral', 'Lawfull Neutral'), ('true_neutral', 'True Neutral'), ('chaotic_neutral', 'Chaotic Neutral'), ('lawfull_evil', 'Lawfull Evil'), ('neutral_evil', 'Neutral Evil'), ('chaotic_evil', 'Chaotic Evil')], default='true_neutral', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.characterrole', verbose_name='Character Role')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STRENGTH', 'Strength'), ('AGILITY', 'Agility'), ('ENDURANCE', 'Endurance'), ('CHARISMA', 'Charisma'), ('INTELLIGENCE', 'Intelligence'), ('WISDOM', 'Wisdom')], max_length=30)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='characters.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'character'), name='unique_character_ability')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACROBATICS', 'Acrobatics'), ('ALCHEMY', 'Alchemy'), ('ANIMAL_HANDLING', 'Animal Handling'), ('ASTUTENESS', 'Astuteness'), ('ATHLETICS', 'Athletics'), ('COOKING', 'Cooking'), ('CRAFT', 'Craft'), ('DARK_PERCEPTION', 'Dark Perception'), ('DECEPTION', 'Deception'), ('DESTRUCTIVE_MAGIC', 'Destructive Magic'), ('ENGINEERING', 'Engineering'), ('ETIQUETTE', 'Etiquette'), ('EXPLOSIVES', 'Explosives'), ('GAMBLING', 'Gambling'), ('HISTORY', 'History'), ('HORSEBACK_RIDING', 'Horseback Riding'), ('INTIMIDATION', 'Intimidation'), ('LEADERSHIP', 'Leadership'), ('LIGHT_MAGIC', 'Light Magic'), ('LINGUISTICS', 'Linguistics'), ('LOCKPICKING', 'Lockpicking'), ('MEDICINE', 'Medicine'), ('MUSIC', 'Music'), ('NATURE', 'Nature'), ('OCCULTISM', 'Occultism'), ('PERCEPTION', 'Perception'), ('PERSUASION', 'Persuasion'), ('POLITICS', 'Politics'), ('PSIONICS', 'Psionics'), ('PUNCH_POWER', 'Punch Power'), ('RELIGION', 'Religion'), ('RESISTANCE', 'Resistance'), ('SAILING', 'Sailing'), ('SCIENCE', 'Science'), ('SEDUCTION', 'Seduction'), ('SELF_CONTROL', 'Self Control'), ('SHOT_POWER', 'Shot Power'), ('SLEIGHT_OF_HAND', 'Sleight Of Hand'), ('SPEECH', 'Speech'), ('STEALTH', 'Stealth'), ('SURVIVAL', 'Survival'), ('TACTICS', 'Tactics'), ('THROWING', 'Throwing'), ('TRADING', 'Trading'), ('TRAPS', 'Traps'), ('UNARMED', 'Unarmed'), ('VELOCITY', 'Velocity'), ('WEAPON_HANDLING', 'Weapon Handling'), ('WITCHCRAFT', 'Witchcraft')], max_length=30)),
                ('type', models.CharField(choices=[('COGNITIVE', 'Cognitive'), ('PHYSICAL', 'Physical'), ('SOCIAL', 'Social')], max_length=30)),
                ('value', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'character'), name='unique_character_skill')],
            },
        ),
    ]
