# Generated by Django 5.1.3 on 2025-01-28 22:38

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Character Role',
                'verbose_name_plural': 'Character Roles',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.characters.models.Character.avatar_path)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alignment', models.CharField(choices=[('lawfull_good', 'Lawfull Good'), ('neutral_good', 'Neutral Good'), ('chaotic_good', 'Chaotic Good'), ('lawfull_neutral', 'Lawfull Neutral'), ('true_neutral', 'True Neutral'), ('chaotic_neutral', 'Chaotic Neutral'), ('lawfull_evil', 'Lawfull Evil'), ('neutral_evil', 'Neutral Evil'), ('chaotic_evil', 'Chaotic Evil')], default='true_neutral', max_length=15)),
                ('strength', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('agility', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('endurance', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('charisma', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('intelligence', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('wisdom', apps.characters.models.StatsField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('acrobatics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('athletics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('weapon_handling', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('sleight_of_hand', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('stealth', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('self_control', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('horseback_riding', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('velocity', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('lockpicking', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('unarmed', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('resistance', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('shot_power', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('punch_power', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('throwing', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('religion', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('explosives', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('alchemy', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('cooking', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('occultism', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('traps', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('politics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('light_magic', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('destructive_magic', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('animal_handling', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('history', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('medicine', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('astuteness', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('nature', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('perception', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('survival', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('sailing', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('engineering', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('tactics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('science', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('dark_perception', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('psionics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('witchcraft', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('craft', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('deception', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('intimidation', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('persuasion', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('speech', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('leadership', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('seduction', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('trading', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('etiquette', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('linguistics', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('music', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('gambling', apps.characters.models.SkillField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.characterrole', verbose_name='Character Role')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
    ]
